---
title: Arctic Fox
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: 'Jekyll Theme Demo

'
baseurl: "/"
url: http://diezcami.github.io
twitter_username: username
github_username: username
markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions:
  - tables
  - autolink
  - strikethrough
  - space_after_headers
  - fenced_code_blocks
